name: MinecraftVideo
main: com.aaaaahhhhhhh.bananapuncher714.minecraftvideo.MinecraftVideo
version: 1.0.0
description: Play videos in Minecraft
author: BananaPuncher714
api-version: 1.13
commands:
  video:
    description: Play videos