name: MinecraftVideo
main: io.github.bananapuncher714.minecraftvideo.MinecraftVideo
version: 0.1
author: BananaPuncher714
authors:
- "jetp250"
description: Play videos
commands:
    vlc:
        description: Indivudual video command
    video:
        description: Toggles private crafting